[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18.18.2" }  # Optional but safer
[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"
